# GitHub Actions workflow for backend deployment
name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - 'GenVolt_Webapp/backend/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: genvolt-backend
  AZURE_WEBAPP_PACKAGE_PATH: 'GenVolt_Webapp/backend'
  NODE_VERSION: '20'

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json

      - name: Create deployment package
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          # Create deployment zip with only necessary files
          zip -r ../backend-deploy.zip \
            app.js \
            server.js \
            startup.sh \
            debug-env.js \
            package.json \
            package-lock.json \
            src/ \
            web.config \
            .deployment \
            deploy.cmd \
            -x "node_modules/*" "*.log" "test_*" ".git*" ".env*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: GenVolt_Webapp/backend-deploy.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_GENVOLT_BACKEND }}
          package: backend-deploy.zip